INSTALL_DIR=../../install_nn2/c920
INCLUDE_DIR=../../include
LIB_DIR = $(INSTALL_DIR)/lib
INCLUDE = -I./ -I$(INSTALL_DIR)/include -I$(INSTALL_DIR)/include/csinn -I$(INSTALL_DIR)/include/backend -I$(INSTALL_DIR)/include/graph
INCLUDE += -I../utils
CFLAGS += -march=rv64gcv0p7_zfh_xtheadc -mabi=lp64d -mtune=c920
CFLAGS += -ffunction-sections -fdata-sections -Wl,--gc-sections -fopenmp
CFLAGS += -DSHL_BUILD_C920V2 -DSHL_BUILD_REF -DSHL_BUILD_GREF -DSHL_BUILD_RVV -DRISCV_TEST
LIB_NAME = shl_c920
LDFLAGS += -L../../install_nn2/c920/lib -lshl_ref -lm
CC = riscv64-unknown-linux-gnu-gcc


test_objs =

test_objs += maxpool.o
test_objs += avgpool.o
test_objs += dwconv2d.o
test_objs += relu.o
test_objs += leaky_relu.o
test_objs += add.o
#test_objs += mul.o
test_objs += pad.o
test_objs += concat.o
test_objs += fullyconnected.o
test_objs += gemm.o
test_objs += conv2d_1x1s1_gemm.o
test_objs += conv2d_im2col_gemm.o
test_objs += conv2d_winograd.o

utils_objs =

utils_objs += ../utils/test_utils.o

all: csi

csi: $(utils_objs) $(test_objs)

$(utils_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@

$(test_objs): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@
	$(CC) $@ $(CFLAGS) $(BOARD) $(utils_objs) -L$(LIB_DIR) -l$(LIB_NAME) -lc -lm -o $@.elf -lgcov

clean:
	rm -rf  $(test_objs) $(utils_objs) *.a *.asm *.elf *.bin *.asm
